#Importing Data

In [1]:
import pandas as pd

df = pd.read_csv("cleaned_retail_day2.csv")
print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

           InvoiceDate  UnitPrice  CustomerID         Country
0  2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1  2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2  2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3  2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4  2010-12-01 08:26:00       3.39     17850.0  United Kingdom

#Details

In [2]:
print(df.describe())

         Quantity   UnitPrice    CustomerID
count  976.000000  976.000000    976.000000
mean    12.997951    3.048473  15980.289959
std     38.831391    5.965496   1864.742095
min    -24.000000    0.100000  12431.000000
25%      2.000000    1.250000  14307.000000
50%      4.000000    2.025000  16098.000000
75%     12.000000    3.750000  17897.000000
max    600.000000  165.000000  18085.000000

#Transaction Count

In [3]:
df['Country'].value_counts()

Country
United Kingdom    940
France             20
Australia          14
Netherlands         2
Name: count, dtype: int64

#Unique Customers

In [4]:
df['CustomerID'].nunique()

48

#Unique Orders

In [5]:
df['InvoiceNo'].nunique()

65

#Most Customers

In [6]:
df.groupby('Country')['CustomerID'].nunique().sort_values(ascending=False)

Country
United Kingdom    45
Australia          1
France             1
Netherlands        1
Name: CustomerID, dtype: int64