# Data Cleaning and Preprocessing

## Objective

The objective of this notebook is to clean and preprocess the Online Retail dataset before performing exploratory data analysis, cohort analysis, and customer lifetime value analysis.

## Load Dataset

The Online Retail dataset is loaded into a Pandas DataFrame for initial inspection and cleaning.

In [35]:
import pandas as pd

df = pd.read_excel("../data/raw/Online Retail.xlsx",sheet_name="Online Retail",engine="openpyxl")

print(df.shape)

(541909, 8)

In [36]:
df.shape

(541909, 8)

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 40.0+ MB

In [38]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(5268)

In [40]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

In [41]:
df = df.drop_duplicates()
print(df.shape)

(536641, 8)

In [42]:
df = df.dropna(subset=["CustomerID"])
print(df.shape)

(401604, 8)

In [43]:
df.to_csv("../data/cleaned/cleaned_retail_day2.csv",index=False)

In [44]:
df.shape

(401604, 8)

In [45]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

## Transaction Cleaning and Feature Creation

Cancelled transactions and invalid records were removed from the dataset. A Sales feature was then created using Quantity and UnitPrice for subsequent revenue and customer value analysis.

In [46]:
import pandas as pd

df = pd.read_csv("../data/cleaned/cleaned_retail_day2.csv")

print(df.shape)

(401604, 8)

In [47]:
# Check cancelled invoices
df["InvoiceNo"].astype(str).str.startswith("C").sum()
print(df.shape)

(401604, 8)

In [48]:
# Remove cancelled invoices
df = df[~df["InvoiceNo"].astype(str).str.startswith("C")]
print(df.shape)

(392732, 8)

In [49]:
# Remove negative quantities
df = df[df["Quantity"] > 0]

In [50]:
# Remove negative prices
df = df[df["UnitPrice"] > 0]

In [51]:
# Create Sales column
df["Sales"] = df["Quantity"] * df["UnitPrice"]

In [52]:
#Sales column added
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Sales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [53]:
df.shape

(392692, 9)

In [54]:
# Save Day 3 dataset
df.to_csv("../data/cleaned/cleaned_retail_day3.csv", index=False)

## Conclusion

The Online Retail dataset was successfully cleaned and prepared for analysis. Missing customer identifiers, duplicate records, cancelled transactions, and invalid values were removed. A Sales feature was created to support revenue, retention, and customer lifetime value analysis. The cleaned dataset is now ready for EDA, Cohort Analysis, and CLTV Analysis.