#Importing Data

In [1]:
import pandas as pd

df = pd.read_csv("cleaned_retail_day3.csv")
print(df.head())

   InvoiceNo StockCode                          Description  Quantity  \
0     536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1     536365     71053                  WHITE METAL LANTERN         6
2     536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3     536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4     536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

           InvoiceDate  UnitPrice  CustomerID         Country  Sales
0  2010-12-01 08:26:00       2.55     17850.0  United Kingdom  15.30
1  2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34
2  2010-12-01 08:26:00       2.75     17850.0  United Kingdom  22.00
3  2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34
4  2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34

#Details

In [2]:
print(df.describe())

           InvoiceNo       Quantity      UnitPrice     CustomerID  \
count  392692.000000  392692.000000  392692.000000  392692.000000
mean   560590.875047      13.119702       3.125914   15287.843865
std     13087.063759     180.492832      22.241836    1713.539549
min    536365.000000       1.000000       0.001000   12346.000000
25%    549234.000000       2.000000       1.250000   13955.000000
50%    561874.000000       6.000000       1.950000   15150.000000
75%    572061.000000      12.000000       3.750000   16791.000000
max    581587.000000   80995.000000    8142.750000   18287.000000

               Sales
count  392692.000000
mean       22.631500
std       311.099224
min         0.001000
25%         4.950000
50%        12.450000
75%        19.800000
max    168469.600000

#Transaction Count

In [3]:
df['Country'].value_counts()

Country
United Kingdom          349203
Germany                   9025
France                    8326
EIRE                      7226
Spain                     2479
Netherlands               2359
Belgium                   2031
Switzerland               1841
Portugal                  1453
Australia                 1181
Norway                    1071
Italy                      758
Channel Islands            747
Finland                    685
Cyprus                     603
Sweden                     450
Austria                    398
Denmark                    380
Poland                     330
Japan                      321
Israel                     245
Unspecified                241
Singapore                  222
Iceland                    182
USA                        179
Canada                     151
Greece                     145
Malta                      112
United Arab Emirates        68
European Community          60
RSA                         57
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              25
Bahrain                     17
Saudi Arabia                 9
Name: count, dtype: int64

#Unique Customers

In [4]:
df['CustomerID'].nunique()

4338

#Unique Orders

In [5]:
df['InvoiceNo'].nunique()

18532

#Most Customers

In [6]:
df.groupby('Country')['CustomerID'].nunique().sort_values(ascending=False)

Country
United Kingdom          3920
Germany                   94
France                    87
Spain                     30
Belgium                   25
Switzerland               21
Portugal                  19
Italy                     14
Finland                   12
Austria                   11
Norway                    10
Australia                  9
Denmark                    9
Netherlands                9
Channel Islands            9
Japan                      8
Sweden                     8
Cyprus                     8
Poland                     6
Unspecified                4
USA                        4
Canada                     4
Greece                     4
Israel                     3
EIRE                       3
United Arab Emirates       2
Bahrain                    2
Malta                      2
Brazil                     1
Lebanon                    1
Iceland                    1
Czech Republic             1
European Community         1
Saudi Arabia               1
RSA                        1
Lithuania                  1
Singapore                  1
Name: CustomerID, dtype: int64